name: fluttmacs
description: Cross-platform Flutter shell for iosmacs.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  xterm: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  macos:
    generate: true
  image_path: "wasmacs/vendor/emacs/etc/images/icons/hicolor/128x128/apps/emacs.png"

flutter:
  uses-material-design: true
