#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_root="${IOSMACS_EMACS_SOURCE:-${repo_root}/wasmacs/vendor/emacs}"
target_build_root="${IOSMACS_BUILD_ROOT:-${repo_root}/build/emacs-ios-probe}"
native_root="${IOSMACS_NATIVE_HELPER_ROOT:-${repo_root}/build/emacs-native-helpers}"
native_source="${native_root}/runtime-source"
runtime_lisp="${IOSMACS_EMACS_LISP_DIR:-${target_build_root}/source/lisp}"
runtime_etc="${IOSMACS_EMACS_ETC_DIR:-${target_build_root}/source/etc}"
reference_root="$(cd "${repo_root}/../wasmacs" 2>/dev/null && pwd || printf '%s/wasmacs' "${repo_root}")"
reference_lisp="${IOSMACS_REFERENCE_LISP_DIR:-${reference_root}/build/system-lisp-image/root/system/lisp}"
reference_etc="${IOSMACS_REFERENCE_ETC_DIR:-${reference_root}/build/system-lisp-image/root/system/etc}"
jobs="${JOBS:-$(sysctl -n hw.ncpu 2>/dev/null || printf '4')}"
log_dir="${target_build_root}/iosmacs"
log_path="${log_dir}/iosmacs-runtime-lisp.txt"

mkdir -p "${log_dir}"

if [[ ! -d "${runtime_lisp}" ]]; then
  "${repo_root}/scripts/build-emacs-ios-probe.sh"
fi

artifact_lisp="${reference_lisp}"
artifact_etc="${reference_etc}"
if [[ "${IOSMACS_FORCE_NATIVE_LISP:-0}" = "1" || ! -d "${artifact_lisp}" ]]; then
  if [[ ! -d "${native_source}" ]]; then
    mkdir -p "${native_root}"
    rsync -a --delete --exclude .git "${source_root}/" "${native_source}/"
  fi

  if [[ ! -x "${native_source}/configure" ]]; then
    (
      cd "${native_source}"
      ./autogen.sh
    )
  fi

  if [[ ! -f "${native_source}/Makefile" ]]; then
    (
      cd "${native_source}"
      ./configure \
        --without-all \
        --without-x \
        --without-ns \
        --without-dbus \
        --without-gconf \
        --without-gsettings \
        --without-imagemagick \
        --without-native-compilation \
        --without-pop \
        --without-sound \
        --without-threads \
        --without-tree-sitter \
        --with-modules=no
    )
  fi

  make -C "${native_source}/lib" all -j"${jobs}"
  make -C "${native_source}/lib-src" make-docfile make-fingerprint -j"${jobs}"
  make -C "${native_source}/src" bootstrap-emacs -j"${jobs}"
  ln -sf bootstrap-emacs "${native_source}/src/emacs"
  artifact_lisp="${native_source}/lisp"
  artifact_etc="${native_source}/etc"
  if ! make -C "${native_source}/lisp" compile-main autoloads finder-data custom-deps -j"${jobs}"; then
    if [[ ! -d "${reference_lisp}" ]]; then
      echo "error: native lisp artifact generation failed and no reference lisp is available" >&2
      echo "missing reference: ${reference_lisp}" >&2
      exit 1
    fi
    artifact_lisp="${reference_lisp}"
    artifact_etc="${reference_etc}"
  fi
else
  artifact_lisp="${reference_lisp}"
  artifact_etc="${reference_etc}"
fi

if [[ ! -f "${artifact_lisp}/loaddefs.el" ]]; then
  echo "error: lisp loaddefs are unavailable: ${artifact_lisp}/loaddefs.el" >&2
  exit 1
fi

rsync -a \
  --include='*/' \
  --exclude='/loadup.el' \
  --exclude='/startup.el' \
  --include='*.el' \
  --exclude='*' \
  "${artifact_lisp}/" "${runtime_lisp}/"

rsync -a \
  --include='*/' \
  --exclude='/loadup.elc' \
  --exclude='/startup.elc' \
  --include='*.elc' \
  --exclude='*' \
  "${artifact_lisp}/" "${runtime_lisp}/"
find "${runtime_lisp}" -type f \( -name '*.el' -o -name '*.elc' \) -exec touch {} +

while IFS= read -r source_file; do
  rel="${source_file#"${runtime_lisp}/"}"
  base="$(basename "${source_file}")"
  shim="${runtime_lisp}/${base}"
  if [[ "${rel}" == "${base}" || -e "${shim}" || -e "${shim}c" ]]; then
    continue
  fi
  module="${rel%.el}"
  cat >"${shim}" <<EOF
;;; ${base} --- iosmacs bundled Lisp shim -*- lexical-binding: t; -*-

;;; Commentary:
;; Generated by prepare-emacs-ios-runtime-lisp.sh.

;;; Code:

(load "${module}" nil nil)

;;; ${base} ends here
EOF
done < <(find "${runtime_lisp}" -mindepth 2 -maxdepth 2 -type f -name '*.el' | sort)

rsync -a "${repo_root}/iosmacs/Emacs/iosmacs-grep.el" "${runtime_lisp}/"

if [[ -d "${artifact_etc}" ]]; then
  rsync -a \
    --include='*/' \
    --include='charsets/***' \
    --include='tutorials/***' \
    --include='HELLO' \
    --include='TUTORIAL*' \
    --include='NEWS*' \
    --include='DOC*' \
    --exclude='*' \
    "${artifact_etc}/" "${runtime_etc}/"
fi

el_count="$(find "${runtime_lisp}" -type f -name '*.el' | wc -l | tr -d ' ')"
elc_count="$(find "${runtime_lisp}" -type f -name '*.elc' | wc -l | tr -d ' ')"
loaddefs_count="$(find "${runtime_lisp}" -type f -name '*loaddefs.el' | wc -l | tr -d ' ')"

if [[ "${el_count}" -eq 0 || "${elc_count}" -eq 0 || "${loaddefs_count}" -eq 0 ]]; then
  echo "error: runtime lisp requires .el, .elc, and generated loaddefs" >&2
  echo "el=${el_count} elc=${elc_count} loaddefs=${loaddefs_count}" >&2
  exit 1
fi

{
  echo "runtime_lisp=${runtime_lisp}"
  echo "runtime_etc=${runtime_etc}"
  echo "native_emacs=${native_source}/src/bootstrap-emacs"
  echo "artifact_lisp=${artifact_lisp}"
  echo "lisp_el_files=${el_count}"
  echo "lisp_elc_files=${elc_count}"
  echo "loaddefs_files=${loaddefs_count}"
} >"${log_path}"

echo "prepared runtime lisp: ${runtime_lisp} (${el_count} .el, ${elc_count} .elc, ${loaddefs_count} loaddefs)"
